In [43]:
import pandas as pandas_lib
import numpy as numpy_lib
import seaborn as seaboorn_lib

In [44]:
data = pandas_lib.read_csv(r'D:\Coding\Life\Data Files/clean_dataa.csv')

In [45]:
data

userId  movieId  rating                      title  \
0           1        2     3.5             Jumanji (1995)   
1           5        2     3.0             Jumanji (1995)   
2          13        2     3.0             Jumanji (1995)   
3          29        2     3.0             Jumanji (1995)   
4          34        2     3.0             Jumanji (1995)   
...       ...      ...     ...                        ...   
99995     696     1152     3.0  He Walked by Night (1948)   
99996     696     5143     2.0    Lone Ranger, The (1956)   
99997     697     4111     3.5    Gardens of Stone (1987)   
99998     697     5174     4.0          Field, The (1990)   
99999     700    69069     3.5            Fired Up (2009)   

                           genres  TotalRatingCount  
0      Adventure|Children|Fantasy               112  
1      Adventure|Children|Fantasy               112  
2      Adventure|Children|Fantasy               112  
3      Adventure|Children|Fantasy               112  
4      Adventure|Children|Fantasy               112  
...                           ...               ...  
99995    Crime|Film-Noir|Thriller                 1  
99996           Adventure|Western                 1  
99997                   Drama|War                 1  
99998                       Drama                 1  
99999                      Comedy                 1  

[100000 rows x 6 columns]

In [46]:
len(set(data['title']))

8225

In [47]:
data.columns

Index(['userId', 'movieId', 'rating', 'title', 'genres', 'TotalRatingCount'], dtype='object')

In [48]:
p_table = data.pivot_table(index='title',columns='userId',values='rating').fillna(0)

In [49]:
p_table

userId                                   1    2    3    4    5    6    7    \
title                                                                        
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Til There Was You (1997)                0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'burbs, The (1989)                       0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...                                      ...  ...  ...  ...  ...  ...  ...   
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  0.0  0.0  0.0  0.0   
eXistenZ (1999)                          0.0  0.0  0.0  0.0  0.0  0.0  0.0   
xXx (2002)                               0.0  0.0  0.0  0.0  0.0  0.0  0.0   
xXx: State of the Union (2005)           0.0  0.0  0.0  0.0  0.0  0.0  0.0   
¡Three Amigos! (1986)                    0.0  0.0  0.0  0.0  0.0  0.0  2.0   

userId                                   8    9    10   ...  693  694  695  \
title                                                   ...                  
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Til There Was You (1997)                0.0  0.0  0.0  ...  0.0  0.0  0.0   
'burbs, The (1989)                       0.0  0.0  0.0  ...  0.0  0.0  0.0   
...                                      ...  ...  ...  ...  ...  ...  ...   
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  ...  0.0  0.0  0.0   
eXistenZ (1999)                          0.0  0.0  0.0  ...  0.0  0.0  0.0   
xXx (2002)                               0.0  0.0  0.0  ...  0.0  0.0  0.0   
xXx: State of the Union (2005)           0.0  0.0  0.0  ...  0.0  0.0  0.0   
¡Three Amigos! (1986)                    0.0  0.0  0.0  ...  0.0  4.0  0.0   

userId                                   696  697  698  699  700  701  702  
title                                                                       
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Til There Was You (1997)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'burbs, The (1989)                       0.0  0.0  0.0  0.0  3.5  0.0  0.0  
...                                      ...  ...  ...  ...  ...  ...  ...  
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
eXistenZ (1999)                          0.0  0.0  0.0  0.0  0.0  0.0  0.0  
xXx (2002)                               0.0  0.0  0.0  0.0  0.0  0.0  0.0  
xXx: State of the Union (2005)           0.0  0.0  0.0  0.0  0.0  0.0  0.0  
¡Three Amigos! (1986)                    3.0  0.0  0.0  0.0  0.0  0.0  0.0  

[8225 rows x 702 columns]

In [ ]:
p_table[1][1]=5
p_table[1][2]=5
p_table[2][1]=5

In [50]:
p_table.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [51]:
from scipy.sparse import csr_matrix

In [52]:
features_mat = csr_matrix(p_table)

In [53]:
features_mat

<8225x702 sparse matrix of type '<class 'numpy.float64'>'
	with 99997 stored elements in Compressed Sparse Row format>

COLLABORATIVE MODEL

In [54]:
from sklearn.neighbors import NearestNeighbors

In [55]:
Model = NearestNeighbors(metric='cosine',algorithm='brute')

In [56]:
Model.fit(features_mat)

NearestNeighbors(algorithm='brute', metric='cosine')

In [57]:
query_index = numpy_lib.random.choice(p_table.shape[0])

In [58]:
query_index

3508

In [59]:
numpy_lib.random.choice(p_table.shape[0])

6338

In [60]:
p_table.shape[0]

8225

In [61]:
p_table.iloc[4877,:].values.reshape(-1,1)

array([[0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
       [0. ],
      

In [62]:
distances,indixes = Model.kneighbors(p_table.iloc[4877,:].values.reshape(1,-1),n_neighbors=10)

In [63]:
distances

array([[0.        , 0.28773661, 0.34829952, 0.39002012, 0.39802066,
        0.41717759, 0.41862412, 0.42407606, 0.46554546, 0.46815289]])

In [64]:
indixes

array([[4877, 4627, 6895,  329, 8083,   66, 3794, 7354, 2861, 4128]],
      dtype=int64)

In [65]:
indixes.flatten()

array([4877, 4627, 6895,  329, 8083,   66, 3794, 7354, 2861, 4128],
      dtype=int64)

final task

In [66]:
p_table.index[4877]

'Mission: Impossible - Ghost Protocol (2011)'

In [67]:
p_table.iloc[indixes.flatten()]

userId                                       1    2    3    4    5    6    \
title                                                                       
Mission: Impossible - Ghost Protocol (2011)  0.0  0.0  0.0  0.0  0.0  0.0   
Man of Steel (2013)                          0.0  0.0  0.0  0.0  0.0  0.0   
Star Trek Into Darkness (2013)               0.0  0.0  0.0  0.0  0.0  0.0   
Amazing Spider-Man, The (2012)               0.0  0.0  0.0  0.0  0.0  0.0   
Wolverine, The (2013)                        0.0  0.0  0.0  0.0  0.0  0.0   
21 Jump Street (2012)                        0.0  0.0  0.0  0.0  0.0  0.0   
Iron Man 3 (2013)                            0.0  0.0  0.0  0.0  0.0  0.0   
Thor: The Dark World (2013)                  0.0  0.0  0.0  0.0  0.0  0.0   
Gangster Squad (2013)                        0.0  0.0  0.0  0.0  0.0  0.0   
La Luna (2011)                               0.0  0.0  0.0  0.0  0.0  0.0   

userId                                       7    8    9    10   ...  693  \
title                                                            ...        
Mission: Impossible - Ghost Protocol (2011)  0.0  0.0  0.0  0.0  ...  0.0   
Man of Steel (2013)                          0.0  0.0  0.0  0.0  ...  0.0   
Star Trek Into Darkness (2013)               0.0  0.0  0.0  0.0  ...  0.0   
Amazing Spider-Man, The (2012)               0.0  0.0  0.0  0.0  ...  0.0   
Wolverine, The (2013)                        0.0  0.0  0.0  0.0  ...  0.0   
21 Jump Street (2012)                        0.0  0.0  0.0  0.0  ...  0.0   
Iron Man 3 (2013)                            0.0  0.0  0.0  0.0  ...  0.0   
Thor: The Dark World (2013)                  0.0  0.0  0.0  0.0  ...  0.0   
Gangster Squad (2013)                        0.0  0.0  0.0  0.0  ...  0.0   
La Luna (2011)                               0.0  0.0  0.0  0.0  ...  0.0   

userId                                       694  695  696  697  698  699  \
title                                                                       
Mission: Impossible - Ghost Protocol (2011)  0.0  0.0  0.0  0.0  0.0  0.0   
Man of Steel (2013)                          0.0  0.0  0.0  0.0  0.0  0.0   
Star Trek Into Darkness (2013)               0.0  0.0  0.0  0.0  0.0  0.0   
Amazing Spider-Man, The (2012)               0.0  0.0  0.0  0.0  0.0  0.0   
Wolverine, The (2013)                        0.0  0.0  0.0  0.0  0.0  0.0   
21 Jump Street (2012)                        0.0  0.0  0.0  0.0  0.0  0.0   
Iron Man 3 (2013)                            0.0  0.0  0.0  0.0  0.0  0.0   
Thor: The Dark World (2013)                  0.0  0.0  0.0  0.0  0.0  0.0   
Gangster Squad (2013)                        0.0  0.0  0.0  0.0  0.0  0.0   
La Luna (2011)                               0.0  0.0  0.0  0.0  0.0  0.0   

userId                                       700  701  702  
title                                                       
Mission: Impossible - Ghost Protocol (2011)  0.0  0.0  0.0  
Man of Steel (2013)                          0.0  0.0  0.0  
Star Trek Into Darkness (2013)               0.0  0.0  0.0  
Amazing Spider-Man, The (2012)               0.0  0.0  0.0  
Wolverine, The (2013)                        0.0  0.0  0.0  
21 Jump Street (2012)                        0.0  0.0  0.0  
Iron Man 3 (2013)                            0.0  0.0  0.0  
Thor: The Dark World (2013)                  0.0  0.0  0.0  
Gangster Squad (2013)                        0.0  0.0  0.0  
La Luna (2011)                               0.0  0.0  0.0  

[10 rows x 702 columns]

In [68]:
distances.flatten()

array([0.        , 0.28773661, 0.34829952, 0.39002012, 0.39802066,
       0.41717759, 0.41862412, 0.42407606, 0.46554546, 0.46815289])

In [69]:
for i in range(0,len(distances.flatten())):
    if i==0:
        print('Reccomendation for {0}'.format(p_table.index[query_index]))
    else:
        print('{} : {} , with a distance of {}'.format(i,p_table.index[indixes.flatten()[i]],distances.flatten()[i]))

Reccomendation for House on Haunted Hill (1999)
1 : Man of Steel (2013) , with a distance of 0.28773661090602154
2 : Star Trek Into Darkness (2013) , with a distance of 0.34829952465499936
3 : Amazing Spider-Man, The (2012) , with a distance of 0.39002012401165476
4 : Wolverine, The (2013) , with a distance of 0.3980206565667609
5 : 21 Jump Street (2012) , with a distance of 0.4171775880741735
6 : Iron Man 3 (2013) , with a distance of 0.418624116237839
7 : Thor: The Dark World (2013) , with a distance of 0.42407606400670717
8 : Gangster Squad (2013) , with a distance of 0.46554546366088023
9 : La Luna (2011) , with a distance of 0.46815288653274245
